sudo: required
services:
  - docker

before_install:
  - docker build -t brianenno/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brianenno/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-154450049532"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY